run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 170
    statements: 80
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - fmt
          - github.com/agrison/go-commons-lang/stringUtils
          - github.com/stretchr/testify/require
          - github.com/cheggaaa/pb
          - testing
          - errors
          - unicode
          - strings
          - strconv
          - sort
          - sync
          - math/rand
          - time
          - go.uber.org/goleak
          - io
          - math
          - os
          - flag
          - bytes
          - regexp
          - bufio
          - github.com/goccy/go-json
          - archive/zip
          - reflect
          - encoding/json
          - net
          - syscall
          - github.com/sirupsen/logrus
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/api/pb
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/logger
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/mapper
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/model
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/service
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/service/memory
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/service/sql
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/storage/sql
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/storage/repository
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/storage/memory
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/storage/model
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/server/http
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/server/grpc
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/config
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/app
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/utils
          - github.com/Serega2780/otus-golang-hw/hw12_13_14_15_calendar/internal/rabbitmq
          - google.golang.org/protobuf/types/known/timestamppb
          - google.golang.org/protobuf/types/known/emptypb
          - google.golang.org/grpc/test/bufconn
          - github.com/go-kit/log
          - github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/logging
          - google.golang.org/grpc/reflection
          - github.com/golang/protobuf/ptypes/empty
          - google.golang.org/grpc/status
          - google.golang.org/grpc
          - google.golang.org/protobuf/proto
          - github.com/rabbitmq/amqp091-go
          - github.com/gorilla/mux
          - gopkg.in/yaml.v3
          - github.com/pressly/goose/v3
          - github.com/jackc/pgx/v4/stdlib
          - database/sql
          - github.com/google/uuid


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
