logger:
  level: info
  format: json
  file: calendar.log
  logToFile: true
  logToConsole: true
isInMemory: false

db:
  user: calendar
  password: calendar
  dbname: calendar
  host: localhost
  port: 5432
  migration: migrations

http:
  ip: 0.0.0.0
  port: 8585

grpc:
  ip: 0.0.0.0
  port: 6565
