apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  initdb.sql: |
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  POSTGRES_USER: calendar
  POSTGRES_PASSWORD: calendar
  POSTGRES_DB: calendar
