apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calendar.fullname" . }}
  labels:
    {{- include "calendar.labels" . | nindent 4 }}
data:
  LOGGER_LEVEL: info
  LOGGER_FORMAT: json
  LOGGER_LOG_TO_FILE: "false"
  LOGGER_LOG_TO_CONSOLE: "true"
  IS_IN_MEMORY: "false"
  DB_USER: calendar
  DB_PASSWORD: calendar
  DB_DBNAME: calendar
  DB_HOST: calendar-postgres
  DB_PORT: "5432"
  DB_MIGRATION: ./
  HTTP_IP: 0.0.0.0
  HTTP_PORT: "8585"
  GRPC_IP: 0.0.0.0
  GRPC_PORT: "6565"
